---
title: "SP KPI Dashboard"
date: today
format:
  dashboard:
    theme: cosmo
    scrolling: true
    include-in-header:
      text: |
        <style>
          .navbar { display: none !important; }
          .quarto-dashboard-content { margin-top: 0 !important; }
        </style>
execute:
  echo: false
  warning: false
  message: false
jupyter: sp-analysis
---

```{python}
#| include: false
from sp_analysis import load_data, prepare_by_kpi_all_countries, facet_chart_by_country, KPI_LABELS
df = load_data()
ALL_KPIS = list(KPI_LABELS.keys())
long_df = prepare_by_kpi_all_countries(df, ALL_KPIS)
```

# {.sidebar}

**Countries**

---

<nav class="nav flex-column nav-pills">

  <a class="nav-link" href="">Home</a>
  <a class="nav-link" href="#austria">Austria</a>
  <a class="nav-link" href="#belgium">Belgium</a>
  <a class="nav-link" href="#switzerland">Switzerland</a>
  <a class="nav-link" href="#czecha">Czecha</a>
  <a class="nav-link" href="#germany">Germany</a>
  <a class="nav-link" href="#greece">Greece</a>
  <a class="nav-link" href="#finland">Finland</a>
  <a class="nav-link" href="#france">France</a>
  <a class="nav-link" href="#croatia">Croatia</a>
  <a class="nav-link" href="#hungary">Hungary</a>
  <a class="nav-link" href="#ireland">Ireland</a>
  <a class="nav-link" href="#iceland">Iceland</a>
  <a class="nav-link" href="#italy">Italy</a>
  <a class="nav-link" href="#lithuania">Lithuania</a>
  <a class="nav-link" href="#netherlands">Netherlands</a>
  <a class="nav-link" href="#norway">Norway</a>
  <a class="nav-link" href="#macedonia">North Macedonia</a>
  <a class="nav-link" href="#portugal">Portugal</a>
  <a class="nav-link" href="#sweden">Sweden</a>
  <a class="nav-link" href="#slovenia">Slovenia</a>
  <a class="nav-link" href="#slovakia">Slovakia</a>
  <a class="nav-link" href="#united-kingdom">United Kingdom</a>
</nav>

# Home

<h1>CESSDA KPI validation dashboard</h1>

Thanks to your contributions, CESSDA has now collected key performance indicators (C-KPIs) for 2025 to measure our progress and impact within the European Research Area. 

This dashboard supports the validation of C-KPI data. 

Here are some general instructions for navigating the country pages:

  - **Left sidebar**: Select your country to view the SP-specific dashboard
  - **Top right corner [...]**: Download your dashboard as an image or view source code
  - **Legends**: 
    - [Blue]{style="color: steelblue;"}: Validated data
    - [Grey]{style="color: grey;"}: 2025 data pending validation
    - [Red]{style="color: red;"}: Missing/unavailable data (displayed as outlier)
  - **Note**: Please refer to the validation Excel file for the categorical KPIs (i.e., C-KPI-07, 09, 18, 19a)

<h3>Next steps (to be completed by **2 July 2026**):</h3>

1. Complete this short 3-question feedback [survey](https://forms.gle/KJnVJj9qKyhUJCm87). One response per SP is sufficient.
1. If you identified any errors, please add your comments directly to the [Excel file](https://docs.google.com/spreadsheets/d/1m9Phl1uxPN9hL4zmgSGFMOFs1X-UmjxP/edit?gid=663340094#gid=663340094).

If you have any questions, please contact Lorraine Wong, Senior Science Officer at the CESSDA Main Office: <lorraine.wong@cessda.eu>.

Thank you for your time and input!

# Austria {#austria}

## Row

```{python}
facet_chart_by_country(long_df, 'Austria', title='Austria – AUSSDA')
```


# Belgium {#belgium}

## Row

```{python}
facet_chart_by_country(long_df, 'Belgium', title='Belgium – SODHA')
```


# Czecha {#czecha}

## Row

```{python}
facet_chart_by_country(long_df, 'Czecha', title='Czecha – ČSDA')
```

# Germany {#germany}

## Row

```{python}
facet_chart_by_country(long_df, 'Germany', title='Germany – GESIS')
```


# Greece {#greece}

## Row

```{python}
facet_chart_by_country(long_df, 'Greece', title='Greece – SoDaNet')
```

# Finland {#finland}

## Row

```{python}
facet_chart_by_country(long_df, 'Finland', title='Finland – FSD')
```

# France {#france}

## Row

```{python}
facet_chart_by_country(long_df, 'France', title='France – Progedo')
```

# Croatia {#croatia}

## Row

```{python}
facet_chart_by_country(long_df, 'Croatia', title='Croatia – CROSSDA')
```

# Hungary {#hungary}

## Row

```{python}
facet_chart_by_country(long_df, 'Hungary', title='Hungary – TÁRKI')
```

# Ireland {#ireland}

## Row

```{python}
facet_chart_by_country(long_df, 'Ireland', title='Ireland – ISSDA')
```

# Iceland {#iceland}

## Row

```{python}
facet_chart_by_country(long_df, 'Iceland', title='Iceland – DATICE')
```

# Italy {#italy}

## Row

```{python}
facet_chart_by_country(long_df, 'Italy', title='Italy – DASSI')
```

# Lithuania {#lithuania}

## Row

```{python}
facet_chart_by_country(long_df, 'Lithuania', title='Lithuania – LiDA')
```

# Netherlands {#netherlands}

## Row

```{python}
facet_chart_by_country(long_df, 'Netherlands', title='Netherlands – DANS')
```

# Norway {#norway}

## Row

```{python}
facet_chart_by_country(long_df, 'Norway', title='Norway – Sikt')
```

# Macedonia {#macedonia}

## Row

```{python}
facet_chart_by_country(long_df, 'North Macedonia', title='North Macedonia – MK-DASS')
```

# Portugal {#portugal}

## Row

```{python}
facet_chart_by_country(long_df, 'Portugal', title='Portugal – APIS')
```



# Switzerland {#switzerland}

## Row

```{python}
facet_chart_by_country(long_df, 'Switzerland', title='Switzerland – FORS')
```

# Sweden {#sweden}

## Row

```{python}
facet_chart_by_country(long_df, 'Sweden', title='Sweden – SND')
```

# Slovenia {#slovenia}

## Row

```{python}
facet_chart_by_country(long_df, 'Slovenia', title='Slovenia – ADP')
```

# Slovakia {#slovakia}

## Row

```{python}
facet_chart_by_country(long_df, 'Slovakia', title='Slovakia – SASD')
```

# United Kingdom {#united-kingdom}

## Row

```{python}
facet_chart_by_country(long_df, 'United Kingdom', title='United Kingdom – UKDS')
```
